/*The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55,
Let us list the factors of the first seven triangle numbers:

            1  : 1
            3  : 1,3
            6  : 1,2,3,6
            10 : 1,2,5,10
            15 : 1,3,5,15
            21 : 1,3,7,21
            28 : 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors? */

#include <stdio.h>

void main(void)
{
    long long number = 1,i,j,sum=0;
    int count=0;

    while(count <= 200)
    {
        sum=0;
        for(j=1;j<=number;j++)
        {
            sum+=j;
            //printf("the j is %lld\n",j);

            //printf("the number is %lld\n",number);
        }
         printf("the sum is %lld\n",sum);

         number++;
         count = 0;
         for(i =1; i<=sum;i++)
         {
             if((sum%i)==0)
             {
                 count++;
             }
         }

    }
    printf("the count is %d\n",count);

}
