/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.*/

#include<stdio.h>

void main(void)
{
    int a=0,b=1,sum =0,fib,i;
    for(i=1;i<=4000000;i++)
    {
        fib = a+b;
        a = b;
        b = fib ;
        if(fib%2==0)
        {
           sum +=fib;
        }
        if(fib >= 4000000)
            break;
    }
    printf("Sum %d", sum);
}
